name: Create Tag on Version Change

on:
  push:
    branches:
      - main
    paths:
      - 'custom_components/aeha_climate/manifest.json'

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from JSON
        id: get_version
        run: |
          VERSION=$(jq -r '.version' custom_components/aeha_climate/manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Verificamos si el tag ya existe para evitar duplicados
          if git rev-parse "v${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "El tag v${{ env.VERSION }} ya existe. Saltando..."
          else
            echo "Creando tag v${{ env.VERSION }}"
            git tag "v${{ env.VERSION }}"
            git push origin "v${{ env.VERSION }}"
          fi